# Site Info
title:              ""
description:        ""

author_name:        "everyone"
author_email:       team@neurodata.io

baseurl:            ""
timezone:           America/New_York

highlighter:        pygments
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap
